# Generated by Django 3.1.7 on 2021-05-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('race', models.CharField(max_length=30)),
                ('profession', models.CharField(max_length=30)),
                ('char_trait', models.CharField(max_length=30)),
                ('weapon', models.CharField(max_length=30)),
                ('equipment', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('eye_colour', models.CharField(max_length=30)),
                ('hair_colour', models.CharField(max_length=30)),
                ('star_sign', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=30)),
                ('weight', models.IntegerField()),
                ('origin', models.CharField(max_length=30)),
                ('money', models.CharField(max_length=30)),
                ('userUID', models.CharField(default='0', max_length=30)),
            ],
        ),
    ]
