# Generated by Django 3.1.7 on 2021-05-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='char_trait',
            new_name='armor',
        ),
        migrations.RemoveField(
            model_name='character',
            name='money',
        ),
        migrations.AddField(
            model_name='character',
            name='primary_statistics',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='secondary_statistics',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
